routes/web.php
<?php

use App\Http\Controllers\NotificationController;
use App\Http\Controllers\SiteController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/admin', [\App\Http\Controllers\Admin\AdminController::class, 'index'])
->name('admin.index')
->middleware('auth', 'is_admin');

Route::middleware('auth', 'is_admin')->name('admin.')->prefix('admin')->group(function(){
    Route::get('/categories/search', [\App\Http\Controllers\Admin\CategoryController::class, 'search'])->name('categories.search');
    Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
    Route::get('/posts/search', [\App\Http\Controllers\Admin\PostController::class, 'search'])->name('posts.search');
    Route::resource('posts', \App\Http\Controllers\Admin\PostController::class);
    Route::get('/users/search', [\App\Http\Controllers\Admin\UserController::class, 'search'])->name('users.search');
    Route::resource('users', \App\Http\Controllers\Admin\UserController::class);
}); 

Route::get('/notifications', [\App\Http\Controllers\NotificationController::class, 'index']);

Route::get('/', [\App\Http\Controllers\SiteController::class, 'index'])->name('index');

Route::get('/categories/{category}', [\App\Http\Controllers\SiteController::class, 'category'])->name('category');

Route::get('/posts/{post}', [\App\Http\Controllers\SiteController::class, 'post'])->name('post');

Route::get('/search', [\App\Http\Controllers\SiteController::class, 'search'])->name('search');

app/Models/User.php
<?php

namespace App\Models;

use Laravel\Sanctum\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Validation\Rules\Password;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => ['required'],
            'email' => ['required','unique:users,email'],
            'password' => ['required', Password::min(8)],
            'role' => ['required'],
        ]);

        $data['password'] = bcrypt($request->password);

        User::create($data);

        return redirect()->route('admin.users.index')->with('success', 'User Successfully Added');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('admin.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $data = $request->validate([
            'name' => ['required'],
            'email' => ['required','unique:users,email,' . $user->id],
            'password' => ['nullable', Password::min(8)],
            'role' => ['required'],
        ]);

        if($request->password){
            $data['password'] = bcrypt($request->password);
        }else{
            unset($data['password']);
        }

        

        $user->update($data);

        return redirect()->route('admin.users.index')->with('success', 'User Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('admin.users.index')->with('success', 'User Deleted Added');
    }

    public function search(Request $request)
    {
        $search = $request->q;
        $users = User::where('name', 'LIKE', '%'.$search.'%')->get();
        return view('admin.users.index', compact('users'));
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.app')

@section('content')  
<div class="container">
    <div class="card">
        <div class="card-header bg-dark text-white">Add user</div>
        <div class="card-body">
            <form action="{{route('admin.users.store')}}" method="post">
                @csrf
                <x-input label="Name" type="text" field="name"/>
                <x-input label="E-mail" type="email" field="email"/>
                <x-input label="Password" type="password" field="password"/>
                <label for="role">Role</label>
                <div class="form-group"> 
                    <select name="role" id="role" class="form-control @error('role') is-invalid @enderror">
                        <option disabled selected>Select Role</option>
                        <option value="Admin">Admin</option>
                        <option value="User">User</option>
                    </select>
                    @error('role')
                        <small class="form-text text-danger">{{"*".$message}}</small>
                    @enderror
                </div>
                <input type="submit" class="btn btn-primary" value="Add">
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')

    
<div class="container">
    <x-alert />
    <div class="card">
        <div class="card-header bg-dark text-white">Edit user</div>
        <div class="card-body">
            <form action="{{route('admin.users.update', $user->id)}}" method="post">
                @csrf
                @method('PUT')
                <x-input label="Name" type="text" field="name" current="{{$user->name}}"/>
                <x-input label="E-mail" type="email" field="email" current="{{$user->email}}"/>
                <x-input label="Password" type="password" field="password" />
                <div class="form-group">
                    <label for="role">Role</label>

                    <select name="role" id="role" class="form-control @error('role') is-invalid @enderror" >
                        <option disabled>Select Role</option>
                        <option value="Admin" @if ($user->role == "Admin") selected @endif>Admin</option>
                        <option value="User"  @if ($user->role == "User") selected @endif>User</option>
                    </select>
                    @error('role')
                        <small class="form-text text-danger">{{"*".$message}}</small>
                    @enderror
                </div>
                <input type="submit" class="btn btn-primary" value="Update">
            </form>
        </div>
    </div>
</div>


@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <x-alert />
        <div class="card">
            <div class="card-header bg-dark text-white d-flex justify-content-between">
                <span>All users</span>
                <span class="d-flex">
                    <form action="{{route('admin.users.search')}}">
                        <div class="input-group">
                            <input type="text" name="q" value="{{request('q')}}" class="form-control form-control-sm">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-sm btn-outline-success">Search</button>
                            </div>
                        </div>
                    </form>
                    <a href="{{route('admin.users.create')}}" class="btn btn-sm btn-primary ml-2">Add user</a>
                </span> 
            </div>
            <div class="card-body">
                <table class="table">
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Actions</th>
                    </tr>
                    @foreach ($users as $user)
                        <tr>
                            <td>{{$user->id}}</td>
                            <td>{{$user->name}}</td>
                            <td>{{$user->email}}</td>
                            <td>{{$user->role}}</td>
                            <td>
                                <a href="{{route('admin.users.show', $user->id)}}" class="btn btn-sm btn-info">View</a>
                                <a href="{{route('admin.users.edit', $user->id)}}" class="btn btn-sm btn-success">Edit</a>
                                <form style="display: inline" action="{{route('admin.users.destroy', $user->id)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <input type="submit" class="btn btn-sm btn-danger" value="Delete">
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/users/show.blade.php
@extends('layouts.app')

@section('content')

    
<div class="container">
    <x-alert />
    <div class="card">
        <div class="card-header bg-dark text-white d-flex justify-content-between">
            <span>User Details</span>
            <a class="btn btn-sm btn-primary " href="{{route('admin.users.index')}}">Go Back</a>
        </div>
        <div class="card-body">
            <table class="table">
                <tr>
                    <th>Id</th>
                    <td>{{$user->id}}</td>
                </tr>
                <tr>
                    <th>Title</th>
                    <td>{{$user->name}}</td>
                </tr>
                <tr>
                    <th>Category</th>
                    <td>{{$user->email}}</td>
                </tr>
                <tr>
                    <th>usered By</th>
                    <td>{{$user->password}}</td>
                </tr>
                <tr>
                    <th>Published</th>
                    <td>{{$user->role}}</td>
                </tr>
                <tr>
                    <th>usered Date</th>
                    <td>{{$user->created_at}}</td>
                </tr>
                <tr>
                    <th>Updated Date</th>
                    <td>{{$user->updated_at}}</td>
                </tr>
            </table>
        </div>
    </div>
</div>


@endsection