routes/web.php
<?php

use App\Http\Controllers\NotificationController;
use App\Http\Controllers\SiteController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/admin', [\App\Http\Controllers\Admin\AdminController::class, 'index'])
->name('admin.index')
->middleware('auth', 'is_admin');

Route::middleware('auth', 'is_admin')->name('admin.')->prefix('admin')->group(function(){
    Route::get('/categories/search', [\App\Http\Controllers\Admin\CategoryController::class, 'search'])->name('categories.search');
    Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
    Route::get('/posts/search', [\App\Http\Controllers\Admin\PostController::class, 'search'])->name('posts.search');
    Route::resource('posts', \App\Http\Controllers\Admin\PostController::class);
    Route::get('/users/search', [\App\Http\Controllers\Admin\UserController::class, 'search'])->name('users.search');
    Route::resource('users', \App\Http\Controllers\Admin\UserController::class);
}); 

Route::get('/notifications', [\App\Http\Controllers\NotificationController::class, 'index']);

Route::get('/', [\App\Http\Controllers\SiteController::class, 'index'])->name('index');

Route::get('/categories/{category}', [\App\Http\Controllers\SiteController::class, 'category'])->name('category');

Route::get('/posts/{post}', [\App\Http\Controllers\SiteController::class, 'post'])->name('post');

Route::get('/search', [\App\Http\Controllers\SiteController::class, 'search'])->name('search');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    protected $fillable = ['title', 'image', 'body', 'user_id', 'category_id', 'is_published'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Post;
use App\Models\Category;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\FileUpload;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::with(['user', 'category'])->get();
        return view('admin.posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.posts.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'title'         => ['required'],
            'body'          => ['required'],
            // 'user_id'       => ['required', 'exists:users,id'],
            'category_id'   => ['required', 'exists:categories,id'],
            'is_published'  => ['nullable', 'boolean'],
            'image'         => ['nullable', 'mimes:png,jpeg,jpg,gif'],
        ]);

        $data['user_id'] = auth()->user()->id;
        $data['is_published'] = $request->is_published ? true : false;

        if($request->hasFile('image')){
            $data['image'] = FileUpload::upload($request->file('image'), "images");
        }

        Post::create($data);
        // Post::create([
        //     'title' => $request->title,
        //     'body' => $request->body,
        //     'user_id' => auth()->user()->id,
        //     'category_id' => $request->category_id
        // ]);

        return redirect()->route('admin.posts.index')->with('success', 'Post added successully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('admin.posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = Category::all();
        return view('admin.posts.edit', compact('post', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $data = $request->validate([
            'title'         => ['required'],
            'body'          => ['required'],
            // 'user_id'       => ['required', 'exists:users,id'],
            'category_id'   => ['required', 'exists:categories,id'],
            'is_published' => ['nullable', 'boolean'],
            'image' => ['nullable', 'mimes:jpg,png,jpeg,gif'],
        ]);

        $data['is_published'] = $request->is_published ? true : false;

        if($request->hasFile('image')){
            // $ext = $request->file('image')->extension();
            // $name = Str::random(20) .".". $ext;
            // $request->file('image')->storeAs('public/images' , $name);

            // $data['image'] = "images/". $name;

            $data['image'] = FileUpload::upload($request->file('image'), "images");;

            if($post->image){
                Storage::delete('public/' . $post->image);
            }
        }

        $post->update($data);
        
        // $post->update([
        //     'title' => $request->title,
        //     'body' => $request->body,
        //     // 'user_id' => auth()->user()->id,
        //     'category_id' => $request->category_id
        // ]);

        return redirect()->route('admin.posts.index')->with('success', 'Post updated successully');
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        return redirect()->route('admin.posts.index')->with('success', 'Post deleted successully');
    }

    public function search(Request $request)
    {
        $search = $request->q;

        $posts = Post::where('title', 'LIKE', '%'.$search.'%')->with(['user', 'category'])->get();

        return view('admin.posts.index', compact('posts'));
    }
}

resources/views/admin/posts/create.blade.php
@extends('layouts.app')

@section('content')

    
<div class="container">
    <x-alert />
    <div class="card">
        <div class="card-header bg-dark text-white">Add Post
            <a class="btn btn-sm btn-primary float-right" href="{{route('admin.posts.index')}}">Go Back</a>
        </div>
        <div class="card-body">
            <form action="{{route('admin.posts.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                <x-input field="title"  label="Post Title" />
                <x-input type="textarea" field="body"  label="Post Body" />
                {{-- <x-input field="user_id"  label="User" /> --}}

                <x-input type="file" field="image" label="image" />
                <div class="form-group">
                    <label for="category_id">Category</label>
                    <select 
                        name="category_id" 
                        id="category_id" 
                        class="form-control 
                        @error('category_id')
                            is-invalid
                        @enderror"
                    >
                        <option disabled selected>Select Category</option>

                        @foreach ($categories as $category)                        
                            <option value="{{$category->id}}">{{$category->name}}</option>
                        @endforeach

                    </select>
                    @error('category_id')
                        <small class="form-text text-danger">{{"*".$message}}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <input type="checkbox" name="is_published" id="is_published" value="1">
                    <label for="is_published">Publish this post</label>
                </div>
                <input type="submit" class="btn btn-primary" value="Add">
            </form>
        </div>
    </div>
</div>
<script src="{{asset('js/ckeditor/ckeditor.js')}}"></script>
<script>ClassicEditor
    .create( document.querySelector( '#body' ), {
        
        toolbar: {
            items: [
                'heading',
                '|',
                'bold',
                'underline',
                'italic',
                'link',
                'bulletedList',
                'numberedList',
                '|',
                'insertTable',
                'undo',
                'redo'
            ]
        },
        language: 'en',
        licenseKey: '',
        
        
        
    } )
    .then( editor => {
        window.editor = editor;

        
        
        
    } )
    .catch( error => {
        console.error( 'Oops, something went wrong!' );
        console.error( 'Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:' );
        console.warn( 'Build id: z5yuzh1oluyb-v333vug4xbpc' );
        console.error( error );
    } );
</script>

@endsection

resources/views/admin/posts/edit.blade.php
@extends('layouts.app')

@section('content')

    
<div class="container">
    <x-alert />
    <div class="card">
        <div class="card-header bg-dark text-white">Edit Post
            <a class="btn btn-sm btn-primary float-right" href="{{route('admin.posts.index')}}">Go Back</a>
        </div>
        <div class="card-body">
            <form action="{{route('admin.posts.update', $post)}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <x-input field="title"  label="Post Title" current="{{$post->title}}"/>
                <x-input type="textarea" field="body"  label="Post Body" current="{!! $post->body !!}"/>
                {{-- <x-input field="user_id"  label="User" current="{{$post->user_id}}"/> --}}
                <x-input type="file" field="image" label="image" />


                    <div class="form-group">
                        <label for="category_id">Category</label>
                        <select 
                            name="category_id" 
                            id="category_id" 
                            class="form-control 
                            @error('category_id')
                                is-invalid
                            @enderror"
                        >    
                            @foreach ($categories as $category)  
                                <option 
                                value="{{$category->id}}"
                                @if($post->category_id == $category->id) selected @endif 
                                >
                                    {{$category->name}}
                                </option>       
                            @endforeach
    
                        </select>
                        @error('category_id')
                            <small class="form-text text-danger">{{"*".$message}}</small>
                        @enderror
                    </div>
                    <div class="form-group">
                        <input 
                        type="checkbox" 
                        name="is_published" 
                        id="is_published" 
                        value="1"
                        @if ($post->is_published)
                            checked
                        @endif
                        >
                        <label for="is_published">Publish this post</label>
                    </div>
                <input type="submit" class="btn btn-primary" value="Update">
            </form>
        </div>
    </div>
</div>
<script src="{{asset('js/ckeditor/ckeditor.js')}}"></script>
<script>ClassicEditor
    .create( document.querySelector( '#body' ), {
        
        toolbar: {
            items: [
                'heading',
                '|',
                'bold',
                'underline',
                'italic',
                'link',
                'bulletedList',
                'numberedList',
                '|',
                'insertTable',
                'undo',
                'redo'
            ]
        },
        language: 'en',
        licenseKey: '',
        
        
        
    } )
    .then( editor => {
        window.editor = editor;

        
        
        
    } )
    .catch( error => {
        console.error( 'Oops, something went wrong!' );
        console.error( 'Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:' );
        console.warn( 'Build id: z5yuzh1oluyb-v333vug4xbpc' );
        console.error( error );
    } );
</script>

@endsection

resources/views/admin/posts/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <x-alert />
        <div class="card">
            <div class="card-header bg-dark text-white d-flex justify-content-between">
                <span>All Posts</span>
                <span class="d-flex">
                    <form action="{{route('admin.posts.search')}}">
                        <div class="input-group">
                            <input type="text" name="q" value="{{request('q')}}" class="form-control form-control-sm">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-sm btn-outline-success">Search</button>
                            </div>
                        </div>
                    </form>
                    <a href="{{route('admin.posts.create')}}" class="btn btn-sm btn-primary ml-2">Add Post</a>
                </span> 
            </div>
            <div class="card-body">
                <table class="table">
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>User</th>
                        <th>Category</th>
                        <th>Published</th>
                        <th>Action</th>
                        
                    </tr>
                    @foreach ($posts as $post)
                        <tr>
                            <td>{{$post->id}}</td>
                            <td>{{$post->title}}</td>
                            <td>{{$post->user->name}}</td>
                            <td>{{$post->category->name}}</td>
                            <td>{{$post->is_published ? "Yes" : 'No'}}</td>
                            <td>
                                <a href="{{route('admin.posts.show', $post->id)}}" class="btn btn-sm btn-info">View</a>
                                <a href="{{route('admin.posts.edit', $post->id)}}" class="btn btn-sm btn-success">Edit</a>
                                <form style="display: inline" action="{{route('admin.posts.destroy', $post)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <input type="submit" class="btn btn-sm btn-danger" value="Delete">
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/posts/show.blade.php
@extends('layouts.app')

@section('content')

    
<div class="container">
    <x-alert />
    <div class="card">
        <div class="card-header bg-dark text-white d-flex justify-content-between">
            <span>Post Details</span>
            <a class="btn btn-sm btn-primary " href="{{route('admin.posts.index')}}">Go Back</a>
        </div>
        <div class="card-body">
            <table class="table">
                <tr>
                    <th>Id</th>
                    <td>{{$post->id}}</td>
                </tr>
                <tr>
                    <th>Title</th>
                    <td>{{$post->title}}</td>
                </tr>
                <tr>
                    <th>Body</th>
                    <td>{!! $post->body !!}</td>
                </tr>
                <tr>
                    <th>Image</th>
                    <th>
                        <img src="/storage/{{$post->image}}" alt="" height="100px">
                    </th>
                </tr>
                <tr>
                    <th>Category</th>
                    <td>{{$post->category->name}}</td>
                </tr>
                <tr>
                    <th>Posted By</th>
                    <td>{{$post->user->name}}</td>
                </tr>
                <tr>
                    <th>Published</th>
                    <td>{{$post->is_published ? "Yes" : "No"}}</td>
                </tr>
                <tr>
                    <th>Posted Date</th>
                    <td>{{$post->created_at}}</td>
                </tr>
                <tr>
                    <th>Updated Date</th>
                    <td>{{$post->updated_at}}</td>
                </tr>
            </table>
        </div>
    </div>
</div>


@endsection