routes/web.php
<?php

use App\Http\Controllers\NotificationController;
use App\Http\Controllers\SiteController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/admin', [\App\Http\Controllers\Admin\AdminController::class, 'index'])
->name('admin.index')
->middleware('auth', 'is_admin');

Route::middleware('auth', 'is_admin')->name('admin.')->prefix('admin')->group(function(){
    Route::get('/categories/search', [\App\Http\Controllers\Admin\CategoryController::class, 'search'])->name('categories.search');
    Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
    Route::get('/posts/search', [\App\Http\Controllers\Admin\PostController::class, 'search'])->name('posts.search');
    Route::resource('posts', \App\Http\Controllers\Admin\PostController::class);
    Route::get('/users/search', [\App\Http\Controllers\Admin\UserController::class, 'search'])->name('users.search');
    Route::resource('users', \App\Http\Controllers\Admin\UserController::class);
}); 

Route::get('/notifications', [\App\Http\Controllers\NotificationController::class, 'index']);

Route::get('/', [\App\Http\Controllers\SiteController::class, 'index'])->name('index');

Route::get('/categories/{category}', [\App\Http\Controllers\SiteController::class, 'category'])->name('category');

Route::get('/posts/{post}', [\App\Http\Controllers\SiteController::class, 'post'])->name('post');

Route::get('/search', [\App\Http\Controllers\SiteController::class, 'search'])->name('search');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-dark shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                        @if(auth()->user())
                            @if (auth()->user()->role == "Admin")
                            <li class="nav-item">
                                <a class="nav-link" href="/admin">Dashboard</a>
                            </li>
                            @endif
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('admin.users.index')}}">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('admin.categories.index')}}">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('admin.posts.index')}}">Posts</a>
                        </li>
                        @endif
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item ">
                            <a class="nav-link" href="/notifications">Notifications</a>
                        </li>
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>

        <footer class="bg-dark text-white px-4 py-2">
            <div class="row">
                <div class="col-lg-5 col-md-12 d-flex justify-content-md-center justify-content-sm-center justify-content-lg-start">
                    &copy; NepNews Pvt. Ltd. 2013-2021
                </div>
                <div class="col-lg-7 col-md-12 d-flex justify-content-around ">
                    <a class="footer-links mx-2" href="#">Submit Blog</a>
                    <a class="footer-links mx-2" href="#">About NepNews</a>
                    <a class="footer-links mx-2" href="#">Advertise with us</a>
                    <a class="footer-links mx-2"href="#">Privacy Policy</a>
                    <a class="footer-links mx-2" href="#">Contact</a>
                </div>
            </div>
        </footer>
    </div>
</body>
</html>