routes/web.php
<?php

use App\Http\Controllers\NotificationController;
use App\Http\Controllers\SiteController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/admin', [\App\Http\Controllers\Admin\AdminController::class, 'index'])
->name('admin.index')
->middleware('auth', 'is_admin');

Route::middleware('auth', 'is_admin')->name('admin.')->prefix('admin')->group(function(){
    Route::get('/categories/search', [\App\Http\Controllers\Admin\CategoryController::class, 'search'])->name('categories.search');
    Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
    Route::get('/posts/search', [\App\Http\Controllers\Admin\PostController::class, 'search'])->name('posts.search');
    Route::resource('posts', \App\Http\Controllers\Admin\PostController::class);
    Route::get('/users/search', [\App\Http\Controllers\Admin\UserController::class, 'search'])->name('users.search');
    Route::resource('users', \App\Http\Controllers\Admin\UserController::class);
}); 

Route::get('/notifications', [\App\Http\Controllers\NotificationController::class, 'index']);

Route::get('/', [\App\Http\Controllers\SiteController::class, 'index'])->name('index');

Route::get('/categories/{category}', [\App\Http\Controllers\SiteController::class, 'category'])->name('category');

Route::get('/posts/{post}', [\App\Http\Controllers\SiteController::class, 'post'])->name('post');

Route::get('/search', [\App\Http\Controllers\SiteController::class, 'search'])->name('search');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes, HasFactory;
    protected $fillable = ['name'];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/API/CategoryController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();

        return response()->json($categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => ['required']
        ]);

        Category::create($data);

        return response()->noContent();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return response()->json($category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $data = $request->validate([
            'name' => ['required']
        ]);

        $category->update($data);

        return response()->noContent();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();

        return response()->noContent();
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all(); 
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required']
        ]);

        Category::create([
            'name' => $request->name
        ]);

        return redirect(route('admin.categories.index'))->with('success', 'Category added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('admin.categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $request->validate([
            'name' => ['required']
        ]);

        $category->update([
            'name' => $request->name
        ]);

        return redirect()->route('admin.categories.index')->with('success', 'Category Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        if(count($category->posts)){
            return redirect()->route('admin.categories.index')->with('error', 'Deletion failed !!  Category you want to delete has posts');
        }else{
            $category->delete();
            return redirect()->route('admin.categories.index')->with('success', 'Category Deleted Successfully');

        }
    }

    public function search(Request $request)
    {
        $search = $request->q;

        $categories = Category::where('name', 'LIKE', '%'.$search.'%')->get();

        return view('admin.categories.index', compact('categories'));
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.app')

@section('content')

    
<div class="container">
    <x-alert />
    <div class="card">
        <div class="card-header bg-dark text-white">Add Category
            <a class="btn btn-sm btn-primary float-right" href="{{route('admin.categories.index')}}">Go Back</a>
        </div>
        <div class="card-body">
            <form action="{{route('admin.categories.store')}}" method="post">
                @csrf
                <x-input field="name" type="text" label="Category Name" />
                <input type="submit" class="btn btn-primary" value="Add">
            </form>
        </div>
    </div>
</div>


@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')

    
<div class="container">
    <div class="card">
        <div class="card-header bg-dark text-white">Edit Category</div>
        <div class="card-body">
            <form action="{{route('admin.categories.update', $category->id)}}" method="post">
                @csrf
                @method('PUT')
                <x-input label="Category Name" type="text" field="name" current="{{$category->name}}" />
                <input type="submit" class="btn btn-primary" value="Update">
            </form>
        </div>
    </div>
</div>


@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <x-alert />
        <div class="card">
            <div class="card-header bg-dark text-white d-flex justify-content-between">
                <span>All Categories</span>
                <span class="d-flex">
                    <form action="{{route('admin.categories.search')}}">
                        <div class="input-group">
                            <input type="text" name="q" value="{{request('q')}}" class="form-control form-control-sm">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-sm btn-outline-success">Search</button>
                            </div>
                        </div>
                    </form>
                    <a href="{{route('admin.categories.create')}}" class="btn btn-sm btn-primary ml-2">Add Category</a>
                </span> 
            </div>
            <div class="card-body">
                <table class="table">
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Actions</th>
                    </tr>
                    @foreach ($categories as $category)
                        <tr>
                            <td>{{$category->id}}</td>
                            <td>{{$category->name}}</td>
                            <td>
                                <a href="{{route('admin.categories.show', $category->id)}}" class="btn btn-sm btn-info">View</a>
                                <a href="{{route('admin.categories.edit', $category->id)}}" class="btn btn-sm btn-success">Edit</a>
                                <form style="display: inline" action="{{route('admin.categories.destroy', $category->id)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <input type="submit" class="btn btn-sm btn-danger" value="Delete">
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/categories/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <x-alert />
        <div class="card">
            <div class="card-header bg-dark text-white d-flex justify-content-between">
                <span>{{$category->name}}</span>
            </div>
            <div class="card-body">
                <ul>
                    <li>Produc</li>
                    <li>Produc</li>
                    <li>Produc</li>
                    <li>Produc</li>
                    <li>Produc</li>
                </ul>
            </div>
        </div>
    </div>

@endsection